name: Android CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '19'
        
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: libraryAAR
        path: library/build/outputs/aar/library-release.aar
        if-no-files-found: error
